### ISSUE TITLE
Bulk annotations always cluster

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/slim#330]
I can no longer see individual polygon annotations - they always cluster, to a cluster of 1!

https://andrey-slim-test.web.app/studies/2.25.302737996345872783571112300080988167697/series/1.3.6.1.4.1.5962.99.1.1250863857.1162905243.1637633436401.2.0

<img width="412" height="276" alt="Image" src="https://github.com/user-attachments/assets/0c8021cb-5b87-41ca-9d60-41620b8303cf" />

**Comment by igoroctaviano** [comment]
@fedorov, I’ve pushed a fix to the branch ```fix/regression-4-sep``` (covering both DMV and Slim). Could you please test it?

**Comment by fedorov** [comment]
@igoroctaviano this one is not resolved, based on my testing.

**Comment by igoroctaviano** [comment]
U might need to redeploy if you didn't today.

**Comment by fedorov** [comment]
Sorry, I was busy with other things and tested just now.

I looked at dmv before, and didn't notice the new branch, so I don't know if it was not there in the morning, or I missed it.

Anyway, I redeployed with the dmv fix branch, and this issue is resolved!

It feels like maybe the un-clustering is triggered earlier than it used to, but it's not a deal-breaker I think, maybe it is even better. So - LGTM!

**Comment by geettrue-dev** [comment]
We have also noticed this issue. It may be irrelevant but as per our observation, this issue is specifically encountered with Annotation groups containing more than 1000 annotations.

**Comment by fedorov** [comment]
@geettrue-dev would you be able to test with the `dicom-microscopy-viewer` PR mentioned above? https://github.com/ImagingDataCommons/dicom-microscopy-viewer/pull/219
